name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "master"
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
        node-version: 16
        path: dist/storybook-static
        build_command: SET NODE_OPTIONS=--openssl-legacy-provider && npm run build-storybook